name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Runs when pushing to 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to AWS EC2
      run: |
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@18.216.171.2 << 'EOF'
        cd ~/DevPulse  # Make sure this path is correct
        git pull origin main
        source venv/bin/activate
        nohup uvicorn main:app --host 0.0.0.0 --port 8000 --reload > server.log 2>&1 &
        disown
        exit
      EOF


